steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: $(rubyVersion)
- script: |
    gem install bundler --no-document
  displayName: 'Install bundler'
- script: |
    bundle install --retry=3 --jobs=4
  displayName: 'Install gems'
- script: |
    bundle exec rake
  env:
    BACKLOG_SPACE_ID: $(spaceId)
    BACKLOG_API_KEY: $(apiKey)
  displayName: 'Run test'
