inherit_from: .rubocop_todo.yml

Style/AccessorMethodName:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false
