inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/ModuleLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'Gemfile'

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false
