inherit_from: .rubocop_todo.yml

Style/DoubleNegation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false
